[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install -y libglib2.0-dev:arm64 libostree-dev:arm64 libssl-dev:arm64"
]

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:latest"
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update", 
    "apt-get install -y libglib2.0-dev:armhf libostree-dev:armhf libssl-dev:armhf"
]
